In [38]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [39]:
df = pd.read_csv("student_pass_dataset.csv")

In [40]:
df.shape

(300, 4)

In [41]:
df.head() 

,hours_studied,attendance_pct,previous_score,passed
0,3.7,43,41,0
1,9.5,72,48,1
2,7.3,72,42,1
3,6.0,78,36,1
4,1.6,84,38,0


In [42]:
x = df.drop(["passed"],axis=1)

In [43]:
x.head() 

,hours_studied,attendance_pct,previous_score
0,3.7,43,41
1,9.5,72,48
2,7.3,72,42
3,6.0,78,36
4,1.6,84,38


In [44]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 

In [11]:
x_scaled

array([[-0.42707672, -1.52500797, -1.06771426],
       [ 1.54718867,  0.07542259, -0.68703515],
       [ 0.79832938,  0.07542259, -1.01333153],
       [ 0.35582162,  0.40654615, -1.33962791],
       [-1.14189694,  0.73766972, -1.23086245],
       [-1.14189694,  1.56547863, -0.0344424 ],
       [-1.48228753,  0.02023533, -0.9589488 ],
       [ 1.2748762 , -0.6420118 , -0.36073877],
       [ 0.35582162,  0.95841876,  0.12870579],
       [ 0.73025127, -0.80757358,  0.78129855],
       [-1.61844376, -0.25570097, -1.50277609],
       [ 1.61526678, -1.41463345,  1.16197766],
       [ 1.13871997, -1.58019523,  0.56376763],
       [-0.97170165,  1.51029137, -1.39401064],
       [-1.07381883,  1.06879328,  1.4338913 ],
       [-1.07381883,  0.6272952 ,  1.59703949],
       [-0.66535013, -0.31088824, -1.44839336],
       [ 0.08350916, -1.13869715, -0.68703515],
       [-0.22284237, -1.19388441,  1.16197766],
       [-0.69938919, -0.86276084,  0.99882947],
       [ 0.38986068,  0.13060985, -1.013

In [45]:
y = df["passed"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: passed, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split 
x_train , x_test , y_train , y_test = train_test_split(x_scaled,y,test_size=0.25,random_state=42,stratify=y)

x_train_scaled = scaler.fit_transform(x_train)   # learn + apply on train
x_test_scaled = scaler.transform(x_test)

In [48]:
from sklearn.linear_model import LogisticRegression 
lg = LogisticRegression(max_iter=1000) 

lg.fit(x_train_scaled,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [49]:
y_pred = lg.predict(x_test_scaled)

In [50]:
y_pred

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1])

In [51]:
y_test

289    0
173    0
266    0
177    0
99     0
      ..
140    1
235    1
174    0
36     0
200    1
Name: passed, Length: 75, dtype: int64

In [52]:
from sklearn.metrics import accuracy_score , roc_auc_score , confusion_matrix , classification_report 
print("Accuracy : ",accuracy_score(y_test,y_pred))
print("ROC Accuracy : ",roc_auc_score(y_test,y_pred))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred))
print("Classification Report : ",classification_report(y_test,y_pred))

Accuracy :  0.7333333333333333
ROC Accuracy :  0.7297008547008547
Confusion Matrix :
 [[23 13]
 [ 7 32]]
Classification Report :                precision    recall  f1-score   support

           0       0.77      0.64      0.70        36
           1       0.71      0.82      0.76        39

    accuracy                           0.73        75
   macro avg       0.74      0.73      0.73        75
weighted avg       0.74      0.73      0.73        75

