In [5]:
def sum_multiples(n, k):
    m = (n - 1) // k
    return k * m * (m + 1) // 2

T = int(input())
for _ in range(T):
    N = int(input())
    print(sum_multiples(N, 3) + sum_multiples(N, 5) - sum_multiples(N, 15))

 2
 10


23


 100


2318


In [ ]:
''' 
Sample Input

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika

Sample Output
56.00
'''
n = int(input())
student_marks = {}
for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores
query_name = input()
summ = sum(student_marks[query_name])
avg = summ/len(student_marks[query_name])
print(f"{avg:.2f}")

In [1]:
import numpy as np 

li = [] 
for i in range(7):
    r = list(map(int,input().split()))
    li.append(r)
ar = np.array(li)
print(ar)

 1 2
 1 2
 1 2
 1 2
 1 2
 1 2
 1 2


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [2]:
import numpy as np
ar = np.array([list(map(int, input().split())) for _ in range(7)])
print(ar)

 1 2
 1 2
 1 2
 1 2
 1 2
 1 2
 1 2


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [5]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
n,m,p = map(int,input().split())
nxp = np.array( [list(map(int,input().split())) for _ in range(n)] )
mxp = np.array( [list(map(int,input().split())) for _ in range(m)] )

print(np.concatenate((nxp,mxp),axis=0))

 4 3 2
 1 2
 1 2
 1 2
 1 2
 1 2
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]]


In [9]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
a , b , c = map(int,input().split())
print(np.zeros((a,b,c), dtype = int))
print(np.ones((a,b,c), dtype = int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [12]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
dm = list(map(int,input().split()))
print(np.zeros((dm),dtype = int))
print(np.ones((dm),dtype = int))

 1 2 3 3


[[[[0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]]]]
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]]


In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.eye(3,4))
print()
print(np.eye(3,4, k=1))
print()
print(np.eye(3,4, k=-1))
print()
print(np.eye(3,4, k=2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [21]:
import numpy as np 
np.set_printoptions(legacy='1.13')
n,m = map(int,input().split())

print(np.eye(n,m))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [29]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np
n,m = map(int,input().split())

a = np.array( [list(map(int,input().split())) for _ in range(n)] )
b = np.array( [list(map(int,input().split())) for _ in range(n)] )
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.int.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]


AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [60]:
def minion_game(st):
    # your code goes here
    stuart_score = 0
    stuart = []
    kev = []
    kev_score = 0
    v = ["A","E","I","O","U"]
    for i in range(len(st)):
        for j in range(i+1,len(st)+1):
            if st[i:j][0] not in v:
                stuart.append(st[i:j])
                stuart_score+=1
            else:
                kev.append(st[i:j])
                kev_score+=1
    # print(stuart)  
    print(stuart_score)
    # print(kev) 
    print(kev_score)
        

if __name__ == '__main__':
    s = input()
    minion_game(s)

 NANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANANNANA

314880
209920


In [50]:
h = "hello"
print(h[::-1])
print(h[:3][::-1])
# print(str( reversed(h[:3])))
print("A"=='A')
v = ["A","E","I","O","U"]
print("A" not in v)

olleh
leh
True
False
