In [ ]:
## mulitiplication of 2 matrix:
r1=int(input("Enter row size : "))
c1=int(input("Enter col size : "))
mat1=[]
for i in range (r1) :
    row=[]
    for j in range(c1) :
        row.append(int(input()))
    mat1.append(row)
print("Matrix1 : ",)
print("[",end=" ")
for i in range (r1) :
    for j in range(c1) :
        print(mat1[i][j],end=" ")
    print()
print("]",end=" ")
r2=int(input("Enter row size : "))
c2=int(input("Enter col size : "))
mat2=[]
for i in range (r2) :
    row=[]
    for j in range(c2) :
        row.append(int(input()))
    mat2.append(row)
print("Matrix2 : ")
print("[",end=" ")
for i in range (r2) :
    for j in range(c2) :
        print(mat2[i][j],end=" ")
    print()
print("]",end=" ")
print("\n")
if c1==r2 :
    mat3=[]
    for i in range (r1) :
        row=[]
        for j in range(c2) :
            x=0
            for k in range(r2) :
                x=x+(mat1[i][k]*mat2[k][j])
            row.append(x)
        mat3.append(row)
    print("[",end=" ")
    for i in range(r1) :
        for j in range(c2) :
            print(mat3[i][j],end=" ")
        print()
    print("]",end=" ")
else :
    print("Matrix multiplication is not possible ")

Matrix1 : 
[ 1 2 
3 4 
 ]
Matrix2 : 
[ 1 2 
3 4 
] 

[ 7 10 
15 22 
] 

In [10]:
#addition of  2 matrix:

r1=int(input("Enter row size : "))
c1=int(input("Enter col size : "))
mat1=[]
for i in range (r1) :
    row=[]
    for j in range(c1) :
        row.append(int(input()))
    mat1.append(row)
print("Matrix1 : ")
print("[",end=" ")
for i in range (r1) :
    for j in range(c1) :
        print(mat1[i][j],end=" ")
    print()
print("]",end=" ")
r2=int(input("Enter row size : "))
c2=int(input("Enter col size : "))
mat2=[]
for i in range (r2) :
    row=[]
    for j in range(c2) :
        row.append(int(input()))
    mat2.append(row)
print("Matrix2 : ")
print("[",end=" ")
for i in range (r2) :
    for j in range(c2) :
        print(mat2[i][j],end=" ")
    print()
print("]",end=" ")
print("\n")
if c1==r2 :
    mat3=[]
    for i in range (r1) :
        row=[]
        for j in range(c2) :
            row.append(mat1[i][j]+mat2[i][j])
        mat3.append(row)
    print("[",end=" ")
    for i in range(r1) :
        for j in range(c2) :
            print(mat3[i][j],end=" ")
        print()
    print("]",end=" ")
else :
    print("Matrix addition is not possible ")

Enter row size :  2
Enter col size :  2
 1
 2
 3
 4


Matrix1 : 
[ 1 2 
3 4 
] 

Enter row size :  2
Enter col size :  2
 1
 2
 3
 4


Matrix2 : 
[ 1 2 
3 4 
] 

[ 2 4 
6 8 
] 

In [14]:

#subtraction of 2 matrix:

r1=int(input("Enter row size : "))
c1=int(input("Enter col size : "))
mat1=[]
for i in range (r1) :
    row=[]
    for j in range(c1) :
        row.append(int(input()))
    mat1.append(row)
print("Matrix1 : ")
print("[",end=" ")
for i in range (r1) :
    for j in range(c1) :
        print(mat1[i][j],end=" ")
    print()
print("]",end=" ")
r2=int(input("Enter row size : "))
c2=int(input("Enter col size : "))
mat2=[]
for i in range (r2) :
    row=[]
    for j in range(c2) :
        row.append(int(input()))
    mat2.append(row)
print("Matrix2 : ")
print("[",end=" ")
for i in range (r2) :
    for j in range(c2) :
        print(mat2[i][j],end=" ")
    print()
print("]",end=" ")
print("\n")
if c1==r2 :
    mat3=[]
    for i in range (r1) :
        row=[]
        for j in range(c2) :
            row.append(mat1[i][j]-mat2[i][j])
        mat3.append(row)
    print("[",end=" ")
    for i in range(r1) :
        for j in range(c2) :
            print(mat3[i][j],end=" ")
        print()
    print("]",end=" ")
else :
    print("Matrix addition is not possible ")

Enter row size :  2
Enter col size :  2
 1
 2
 3
 4


Matrix1 : 
[ 1 2 
3 4 
] 

Enter row size :  2
Enter col size :  2
 1
 2
 3
 4


Matrix2 : 
[ 1 2 
3 4 
] 

[ 0 0 
0 0 
] 

In [8]:
#to display Transpose of a matrix 
r=int(input('Enter Row Size:'))
c=int(input('Enter Column Size:'))
m=[]
if r==c:
    for i in range(r):
        row=[]
        for j in  range(c):
            row.append(int(input()))
        m.append(row)
    print('Matrix:\n[ ')
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=" ")
        print()
    print(']',end='')
    print('Transpose Matrix:\n[')
    for i in range(r):
        for j in range(c):
            print(m[j][i],end=" ")
        print()
    print(']')

Matrix:
[ 
1 2 
3 4 
]Transpose Matrix:
[
1 3 
2 4 
]


In [22]:
## diagonal of matrix
r=int(input('Enter row:'))
c=int(input('Enter columns'))
mat=[]
if r==c:
    for i in range(r):
        row=[]
        for j in range(c):
            row.append(int(input()))
        m.append(row)
    print('Matrix:\n[')
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=" " )
        print()
    print(']')
    print('Diagonal element:',end=" ")
    for i in range(r):
        for j in range(c):
            if i==j:
                print(m[i][j],end=" ")
        print(end=" ")
else:
    print('it is not a sqaure matrixzs')

Enter row: 2
Enter columns 2
 1
 2
 3
 4


Matrix:
[
1 2 
3 4 
]
Diagonal element: 1  4  

In [27]:
## trace of matrix
r=int(input('Enter row:'))
c=int(input('Enter columns'))
mat=[]
if r==c:
    for i in range(r):
        row=[]
        for j in range(c):
            row.append(int(input()))
        m.append(row)
    print('Matrix:\n[')
    trace_sum=0
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=" " )
        print()
    print(']')
    print('trace element:',end=" ")
    for i in range(r):
        for j in range(c):
            if i==j:
                print(m[i][j],end=" ")
                trace_sum += m[i][j]
    print(f"\nTrace of matrix (sum): {trace_sum}")
else:
    print('it is not a sqaure matrix')

Enter row: 2
Enter columns 2
 1
 2
 3
 4


Matrix:
[
1 2 
3 4 
]
trace element: 1 4 
Trace of matrix (sum): 5


In [10]:
#1D array
import numpy as np
a1=np.array([2,4,8])
print(a1)

[2 4 8]


In [2]:
print(a1)
print(a1/2)
print(a1*2)

[2 4 8]
[1. 2. 4.]
[ 4  8 16]


In [2]:
#2D array
import numpy as np
a2=np.array([[2,4,6,8],[10,12,14,16]])
print(a2)

[[ 2  4  6  8]
 [10 12 14 16]]


In [3]:
#3D array
import numpy as np
a3=np.array([[2,4,6],[8,10,12],[14,16,18]])
print(a3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [1]:
#determinant ofa matrix
import numpy as np
from numpy.linalg import det
mat1=np.array([[1,2,3],[4,3,6],[7,81,1]])
print("Matrix: ",mat1)
print("Determinant of mat1: ",end=" ")
det_mat1=det(mat1)
print("%d" %(det_mat1))

Matrix:  [[ 1  2  3]
 [ 4  3  6]
 [ 7 81  1]]
Determinant of mat1:  501


In [8]:
#inverse of a matrix
import numpy as np
from numpy.linalg import inv
mat1=np.array([[1,2,3],[4,3,6],[7,8,1]])
print("Matrix: ",mat1)
print("Inverse of matrix:")
inv_mat1=inv(mat1)
print(inv_mat1)

Matrix:  [[1 2 3]
 [4 3 6]
 [7 8 1]]
Inverse of matrix:
[[-0.703125  0.34375   0.046875]
 [ 0.59375  -0.3125    0.09375 ]
 [ 0.171875  0.09375  -0.078125]]


In [12]:
## rank of matraix
import numpy as np 
from  numpy.linalg import matrix_rank
r1=3
c1=3
mat1=[]
for i in range(r1):
    row=[]
    for j in range(c1):
        row.append(int(input()))
    mat1.append(row)
print('Matrix1: ')
print('[',end="")
for i in range(r1):
    for j in range(c1):
        print(mat1[i][j],end=" ")
    print()
print(']')
rank=matrix_rank(mat1)
print("Rank of matrix:",rank)

 2
 2
 2
 2
 2
 2
 2
 2
 2


Matrix1: 
[2 2 2 
2 2 2 
2 2 2 
]
Rank of matrix: 1


In [2]:
# To slove system of equations 3x+y=9,X+2Y=8
import numpy as np
A=np.array([[3,1],[1,2]])
B=np.array([9,8])
Sol=np.linalg.solve(A,B)
print('Solution',Sol)

Solution [2. 3.]


In [6]:
#To solve application problem in system of equations
'''A lady bought 12 apples and 6 bananas for $102 on a specific day (expensive  fruit)
the next day, she bought 10 apples and 10 bananas for $110. Assuming the price of bananas didn't change in two days,what 
is the price of one apple and one bananas 
12a+6b=102,10a+10b=110
'''
import numpy as np 
A=np.array([[12,6],[10,10]])
B=np.array([102,110])
X=np.linalg.solve(A,B)
print('The price of one apple and one banana is ',X)

The price of one apple and one banana is  [6. 5.]


In [9]:
# 2X+3Y+4Z=5,X+2Y+3Z=4,3X-4Y+7Z=10
import numpy as np 
A=np.array([[2,3,4],[1,2,3],[3,-4,7]])
B=np.array([5,4,10])
X=np.linalg.solve(A,B)
print('The Value of x,y and z is: ',X)

The Value of x,y and z is:  [-0.44444444 -0.11111111  1.55555556]


In [2]:
# to find eigen values and eigen vectors 
import sympy as sp
mat=sp.Matrix([[1,3,5],[0,2,7],[0,0,9]])
print(mat)
eigen=mat.eigenvects()
for i in range(3):
    print('\neigen value',eigen[i][0])
    print('\nnumber of times eigen value repeated',eigen[i][1])#No.of times eigen
    print('\neigen vector',eigen[i][2])

Matrix([[1, 3, 5], [0, 2, 7], [0, 0, 9]])

eigen value 1

number of times eigen value repeated 1

eigen vector [Matrix([
[1],
[0],
[0]])]

eigen value 2

number of times eigen value repeated 1

eigen vector [Matrix([
[3],
[1],
[0]])]

eigen value 9

number of times eigen value repeated 1

eigen vector [Matrix([
[1],
[1],
[1]])]


In [4]:
#to find eigen values and eigen vectors
import numpy as np
#create matrix
matrix=np.array([[1,-1,3],[1,1,6],[3,8,9]])
print('square matrix:\n',matrix)
#calculate eigenvalues and eigenvectors(Use numpy's linalg.eig)
eigenvalues, eigenvectors=np.linalg.eig(matrix)
print('\neigen values:\n',eigenvalues)
#if numpy we get normalizzed eigen vectors
print('\nEigen vectors:\n',eigenvectors)


square matrix:
 [[ 1 -1  3]
 [ 1  1  6]
 [ 3  8  9]]

eigen values:
 [13.55075847  0.74003145 -3.29078992]

Eigen vectors:
 [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [5]:
import sympy as sp
import numpy as np


In [11]:
# to find eigen values and eigen vectors 
import sympy as sp
mat=sp.Matrix([[1,-1,2],[1,1,6],[3,8,9]])
print(mat)
eigen=mat.eigenvects()
for i in range(3):
    print('\neigen value',eigen[i][0])
    print('\nnumber of times eigen value repeated',eigen[i][1])#No.of times eigen
    print('\neigen vector',eigen[i][2])

Matrix([[1, -1, 2], [1, 1, 6], [3, 8, 9]])

eigen value 11/3 + (-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3) + 223/(9*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3))

number of times eigen value repeated 1

eigen vector [Matrix([
[-2008/219 - 17171/(657*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3)) + 8*(11/3 + (-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3) + 223/(9*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3)))**2/73 - 77*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3)/73],
[   607/219 + 38*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3)/73 - 3*(11/3 + (-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3) + 223/(9*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3)))**2/73 + 8474/(657*(-1/2 - sqrt(3)*I/2)*(2501/27 + sqrt(59686)*I/3)**(1/3))],
[                                                                                                                                                                              

In [1]:
#to calculate diagonalization of a matrix
import sympy as sp
import numpy as np
A=sp.Matrix([[1,1,1],[0,2,1],[-4,4,3]])
print('Matrix=\n',A)
eigen=A.eigenvects()
print('Eigen values ,NO.of times repeateed , eigen vectors:\n',eigen)
A=np.array([[1,1,1],[0,2,1],[-4,4,3]])
B=np.array([[-1/2,-1,1],[1,1,0],[1,1,1]])
p=B.T
#model matrix
print('Model Matrix\n',p)
pinverse=np.linalg.inv(p)
print('Inverse of P\n',pinverse)
D=pinverse@A@p
print('Diagonal Matrix\n',D)


Matrix=
 Matrix([[1, 1, 1], [0, 2, 1], [-4, 4, 3]])
Eigen values ,NO.of times repeateed , eigen vectors:
 [(1, 1, [Matrix([
[-1/2],
[  -1],
[   1]])]), (2, 1, [Matrix([
[1],
[1],
[0]])]), (3, 1, [Matrix([
[1],
[1],
[1]])])]
Model Matrix
 [[-0.5  1.   1. ]
 [-1.   1.   1. ]
 [ 1.   0.   1. ]]
Inverse of P
 [[ 2. -2. -0.]
 [ 4. -3. -1.]
 [-2.  2.  1.]]
Diagonal Matrix
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [15]:
import sympy as sp
r=int(input('Enter number of rows:'))
c=int(input('Enter number of col:'))
if r==c:
    m=[]
    for i in range(r):
        row=[]
        for j in range(c):
            row.append(int(input()))
        m.append(row)
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=' ')
        print()
    a=sp.Matrix(m)
    ev=a.eigenvals()
    P,D=a.diagonalize()
    print('The eigen values are\n',ev)
    print('The modle matrix:\n',P)
    print('The diagonalize matrix:\n',D)



2 2 
2 2 
The eigen values are
 {4: 1, 0: 1}
The modle matrix:
 Matrix([[-1, 1], [1, 1]])
The diagonalize matrix:
 Matrix([[0, 0], [0, 4]])


In [17]:
import numpy as np
r=int(input('Enter number of rows:'))
c=int(input('Enter number of col:'))
if r==c:
    m=[]
    for i in range(r):
        row=[]
        for j in range(c):
            row.append(int(input()))
        m.append(row)
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=' ')
        print()
    a=np.array(m)
    ev,evc=np.linalg.eig(m)
    print('The eigen value:\n',ev)
    print('The eigen vectors:\n',evc)
else:
    print('it is not a square matrix')


2 2 
2 2 
The eigen value:
 [4.0000000e+00 4.4408921e-16]
The eigen vectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [18]:
import sympy as sp
r=int(input('Enter number of rows:'))
c=int(input('Enter number of col:'))
if r==c:
    m=[]
    for i in range(r):
        row=[]
        for j in range(c):
            row.append(int(input()))
        m.append(row)
    for i in range(r):
        for j in range(c):
            print(m[i][j],end=' ')
        print()
    a=sp.Matrix(m)
    ev=a.eigenvals()
    evc=a.eigenvects()
    print('The eigen value:\n',ev)
    print('The eigen vectors:\n',evc)


2 2 
2 2 
The eigen value:
 {4: 1, 0: 1}
The eigen vectors:
 [(0, 1, [Matrix([
[-1],
[ 1]])]), (4, 1, [Matrix([
[1],
[1]])])]


In [5]:
import numpy as np
l=['a','b','c','d','e']
print(l)
name=np.array(l)
np.random.seed(1)
cgpa = np.array([np.random.random()*10 for x in range(len(name))])
cgpa=np.round(cgpa,2)
print(cgpa)
ind=np.argsort(cgpa)    
print(name[ind])


['a', 'b', 'c', 'd', 'e']
[4.17 7.2  0.   3.02 1.47]
['c' 'e' 'd' 'a' 'b']


In [4]:
#program on solving ODE of first order 
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x)+9*f(x))


Eq(f(x), C1*exp(-9*x))

In [7]:
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x)+cos(x)*f(x)-sin(x)*cos(x))

Eq(f(x), C1*exp(-sin(x)) + sin(x) - 1)

In [9]:
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x)+f(x)*cos(x)-cos(x)*cos(x)*exp(-sin(x)))

Eq(f(x), (C1 + x/2 + sin(2*x)/4)*exp(-sin(x)))

In [12]:
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x)+x*f(x)/(x+1)-exp(x)*(x+1)**4)

Eq(f(x), C1*x*exp(-x)/8 + C1*exp(-x)/8 + x**4*exp(x)/2 + 5*x**3*exp(x)/4 + 3*x**2*exp(x)/2 + 7*x*exp(x)/8 + exp(x)/8)

In [14]:
# Program on ODE of 2nd Order
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x,x)+6*Derivative(f(x),x)+9*f(x))

Eq(f(x), (C1 + C2*x)*exp(-3*x))

In [16]:
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(4*Derivative(f(x),x,x,x)+4*Derivative(f(x),x,x)+Derivative(f(x),x))

Eq(f(x), C1 + (C2 + C3*x)*exp(-x/2))

In [19]:
from sympy import*
from sympy.abc import x
f=Function('f')
dsolve(Derivative(f(x),x,x)+4*f(x)-tan(2*x))

Eq(f(x), C2*sin(2*x) + (C1 + log(sin(2*x) - 1)/8 - log(sin(2*x) + 1)/8)*cos(2*x))

In [ ]:
#program on partial Derivative
from sympy import*
x,y=symbols('x,y')
function=x**2*y**3+12*y+12*y**4
print('Partial derivative w.r.t x=',diff(function,x))
print('partial derivative w.r.t y=',diff(function,y))
print('second order partial derivative w.r.t x=',diff(function,x,x))
print('second order partial derivative w.r.t y and x=',diff(function,y,x))
print('second order partial derivative w.r.t x and y=',diff(function,x,y))
print('second order partial derivative w.r.t y=',diff(function,y,y))


Partial dericative w.r.t x= 2*x*y**3
partial derivative w.r.t y= 3*x**2*y**2 + 48*y**3 + 12
second order partial derivative w.r.t x= 2*y**3
second order partial derivative w.r.t y and x= 6*x*y**2
second order partial derivative w.r.t y= 6*x*y**2
second order partial derivative w.r.t y= 6*y*(x**2 + 24*y)


In [ ]:
#program on jacobian
from sympy import*
x,y,z = symbols('x y z')
print('Give the functions u,v,w in separate lines')
u = input('give the function u:')#u:x+y+z v:x*y*z w:x*y+y*z+z*x
v= input('give the function v:')
w =input('give the function w:')
a1,a2,a3=diff(u,x),diff(u,y),diff(u,z)
b1,b2,b3=diff(v,x),diff(v,y),diff(v,z)
c1,c2,c3=diff(w,x),diff(w,y),diff(w,z)
result=Matrix([[a1,a2,a3],[b1,b2,b3],[c1,c2,c3]])
print(result)
print('The Jacobian of u,v,w with respect to x,y,z is',result.det())

Give the funcitons u,v,w in separate lines
Matrix([[1, 1, 1], [y*z, x*z, x*y], [y + z, x + z, x + y]])
The Jacobian of u,v,w with respect to x,y,z is -x**2*y + x**2*z + x*y**2 - x*z**2 - y**2*z + y*z**2


In [33]:
# program on double intergration
from sympy import*
x,y= symbols('x,y')
#constants limits
print('Double integral with constant limits: ',integrate(x*y,(x,0,1),(y,0,1)))
#variable limits
print('Double integral with variable limits:',integrate(x*y,(x,0,y),(y,0,1)))

Double integral with constant limits:  1/4
Double integral with variable limits: 1/8


In [2]:
#program on triple intergration
from sympy import*
x=symbols('x')
y=symbols('y')
z=symbols('z')
#constant limits
print('Triple integral with constant limits:',integrate(x*y*z,(x,0,1),(y,0,1),(z,0,1)))
#variable limits
print('Triple integral with variable limits:',integrate(exp(z),(z,0,x+y),(y,0,1-x)))

Triple integral with constant limits: 1/8
Triple integral with variable limits: x - exp(x) - 1 + E


In [5]:
#program on gradient for give n function
from sympy import *
from numpy import array
x,y,z=symbols('x,y,z')
f=x*y*z
dx=diff(f,x)
dy=diff(f,y)
dz=diff(f,z)
grad=array([dx,dy,dz])
print('Grandient=',grad)


Grandient= [y*z x*z x*y]


In [8]:
#program on divergence for given function
from sympy import*
from numpy import array
x,y,z=symbols('x,y,z')
variables= symbols('x,y,z')
#Given vector f1*i+f2*j+f3*k
f1=x**3
f2=y**3
f3=x*z
F=array([f1,f2,f3])
s=0
for i in range(3):
    s=s+diff(F[i],variables[i])
print('Divergence=',s)


Divergence= 3*x**2 + x + 3*y**2


In [1]:
#program on curl for given  function
from sympy import*
import numpy as np
from numpy import array
x,y,z=symbols('x,y,z')
#Given vector f1*i+f2*j+f3*k
f1=x*y*z
f2=3*x**2*y
f3=(x*z**2)-(y**2*z)
point={x:1,y:-1,z:1}
i=diff(f3,y)-diff(f2,z)
j=-diff(f3,x)-diff(f1,z)
k=diff(f2,x)-diff(f1,y)
curl=array([i.subs(point),j.subs(point),k.subs(point)])
print('curl=',curl)

curl= [2 0 -7]


In [1]:
# program on angle between the two surfaces at given point
from sympy import*
import numpy as np
def gradient(f,points):
    dx=diff(f,x)
    dy=diff(f,y)
    dz=diff(f,z)
    grad=np.array([dx.subs(points),dy.subs(points),dz.subs(points)])
    return grad
def gradient_norm(grad):
    s=0
    for v in grad:
        s=s+v**2
    return sqrt(s)
x,y,z=symbols('x,y,z')
s1=x**2+y**2+z**2-9
s2=x**2+y**2-z-2
points={x:2,y:-1,z:2}
grad1=gradient(s1,points)
print('Gradiant of surface 1 =',grad1)
grad2=gradient(s2,points)
print('Gradinat of surface 2 =',grad2)
n1=gradient_norm(grad1)                                   #output: Gradiant of surface 1:[4 -2 4]
                                                        # Gradiant of surface 2:[4 -2 -1]
                                                        # theta = acos(8*sqrt(21))
n2=gradient_norm(grad2)
Costheta =np.dot(grad1,grad2)/(n1*n2)
print('Theta=',acos(Costheta))

Gradiant of surface 1 = [4 -2 4]
Gradinat of surface 2 = [4 -2 -1]
Theta= acos(8*sqrt(21)/63)
