In [2]:
#to find eigen values and eigen vectors 
import numpy as np 
#create matrix 
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])
print("Square matrix:\n",matrix)

#Calculate eigenvalues and eigenvectors (Use Numpy's linalg.eig )
eigenvalues , eigenvectors = np.linalg.eig(matrix)

print("\nEigen values:\n",eigenvalues)

#In numpy we get normalized eigen vectors 
print("\neigen Vectors:\n",eigenvectors)

Square matrix:
 [[ 1 -1  3]
 [ 1  1  6]
 [ 3  8  9]]

Eigen values:
 [13.55075847  0.74003145 -3.29078992]

eigen Vectors:
 [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [8]:
import sympy as sp 
mat = sp.Matrix([[1,3,5],
                [0,2,7],
                [0,0,9]])
print(mat)
eigen = mat.eigenvects() 
for i in range(3): 
    print("\neigen value",eigen[i][0])
    print("number of times eigen value repeated",eigen[i][1])
    print("eigen vector",eigen[i][2])

Matrix([[1, 3, 5], [0, 2, 7], [0, 0, 9]])

eigen value 1
number of times eigen value repeated 1
eigen vector [Matrix([
[1],
[0],
[0]])]

eigen value 2
number of times eigen value repeated 1
eigen vector [Matrix([
[3],
[1],
[0]])]

eigen value 9
number of times eigen value repeated 1
eigen vector [Matrix([
[1],
[1],
[1]])]


In [9]:
#to find eigen values and eigen vectors 
import numpy as np 
#create matrix 
matrix = np.array([[1,3,5],
                [0,2,7],
                [0,0,9]])
print("Square matrix:\n",matrix)

#Calculate eigenvalues and eigenvectors (Use Numpy's linalg.eig )
eigenvalues , eigenvectors = np.linalg.eig(matrix)

print("\nEigen values:\n",eigenvalues)

#In numpy we get normalized eigen vectors 
print("\neigen Vectors:\n",eigenvectors)

Square matrix:
 [[1 3 5]
 [0 2 7]
 [0 0 9]]

Eigen values:
 [1. 2. 9.]

eigen Vectors:
 [[1.         0.9486833  0.57735027]
 [0.         0.31622777 0.57735027]
 [0.         0.         0.57735027]]


In [1]:
# Matrix Diagonalization: D = P_inv * A * P
import numpy as np

# Define the original matrix
A = np.array([
    [ 1, 1, 1],
    [ 0, 2, 1],
    [-4, 4, 3]
], dtype=float)

print("Original Matrix A:\n", A)

# Step 1: Compute eigenvalues and normalized eigenvectors directly
eigenvalues, P = np.linalg.eig(A)
# P columns are the normalized eigenvectors automatically

print("\nEigenvalues:\n", eigenvalues)
print("\nModal Matrix P (normalized eigenvectors as columns):\n", P)

# Step 2: Compute inverse of modal matrix
P_inv = np.linalg.inv(P)
print("\nInverse of P:\n", P_inv)

# Step 3: Compute diagonal matrix D = P_inv * A * P
D = P_inv @ A @ P
D_clean = np.round(D.real, decimals=6)  # round off floating point noise
print("\nDiagonal Matrix D:\n", D_clean)

# Step 4: Verify — reconstruct A from D and check
A_reconstructed = P @ D @ P_inv
print("\nReconstructed A (verify):\n", np.round(A_reconstructed.real, decimals=6))
print("\nDiagonalization successful?", np.allclose(A, A_reconstructed.real))

Original Matrix A:
 [[ 1.  1.  1.]
 [ 0.  2.  1.]
 [-4.  4.  3.]]

Eigenvalues:
 [3. 2. 1.]

Modal Matrix P (normalized eigenvectors as columns):
 [[ 5.77350269e-01 -7.07106781e-01  3.33333333e-01]
 [ 5.77350269e-01 -7.07106781e-01  6.66666667e-01]
 [ 5.77350269e-01 -1.13369920e-15 -6.66666667e-01]]

Inverse of P:
 [[-3.46410162  3.46410162  1.73205081]
 [-5.65685425  4.24264069  1.41421356]
 [-3.          3.          0.        ]]

Diagonal Matrix D:
 [[ 3. -0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  1.]]

Reconstructed A (verify):
 [[ 1.  1.  1.]
 [ 0.  2.  1.]
 [-4.  4.  3.]]

Diagonalization successful? True


In [2]:
# Matrix Diagonalization: D = P_inv * A * P

import sympy as sp
import numpy as np

# Define the original matrix
A = sp.Matrix([
    [1, 1,  1],
    [0, 2,  1],
    [-4, 4, 3]
])
print("Original Matrix A:\n", A)

# Step 1: Compute eigenvalues and eigenvectors using SymPy
# eigenvects() returns list of (eigenvalue, multiplicity, [eigenvector])
eigen_data = A.eigenvects()
print("\nEigenvalues, Multiplicity, Eigenvectors:\n", eigen_data)

# Step 2: Build the modal matrix P (columns = eigenvectors)
# Extract eigenvectors and stack them as columns
eigenvectors = [vec for val, mult, vecs in eigen_data for vec in vecs]
modal_matrix = sp.Matrix.hstack(*eigenvectors)  # horizontal stack = column matrix
print("\nModal Matrix P (SymPy):\n", modal_matrix)

# Convert to NumPy for numerical computation
A_numpy = np.array(A.tolist(), dtype=float)
P = np.array(modal_matrix.tolist(), dtype=float ) # modal matrix as numpy array

print("\nModal Matrix P (NumPy):\n", P)

# Step 3: Compute the inverse of the modal matrix
P_inv = np.linalg.inv(P)
print("\nInverse of Modal Matrix (P_inv):\n", P_inv)

# Step 4: Compute the diagonal matrix D = P_inv * A * P
D = P_inv @ A_numpy @ P
print("\nDiagonal Matrix D:\n", np.round(D, decimals=6))  # round to remove floating point noise

Original Matrix A:
 Matrix([[1, 1, 1], [0, 2, 1], [-4, 4, 3]])

Eigenvalues, Multiplicity, Eigenvectors:
 [(1, 1, [Matrix([
[-1/2],
[  -1],
[   1]])]), (2, 1, [Matrix([
[1],
[1],
[0]])]), (3, 1, [Matrix([
[1],
[1],
[1]])])]

Modal Matrix P (SymPy):
 Matrix([[-1/2, 1, 1], [-1, 1, 1], [1, 0, 1]])

Modal Matrix P (NumPy):
 [[-0.5  1.   1. ]
 [-1.   1.   1. ]
 [ 1.   0.   1. ]]

Inverse of Modal Matrix (P_inv):
 [[ 2. -2. -0.]
 [ 4. -3. -1.]
 [-2.  2.  1.]]

Diagonal Matrix D:
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [1]:
#To calculate Diagonalization of a Matrix

import sympy as sp
import numpy as np

A = sp.Matrix([[1,1,1],[0,2,1],[-4,4,3]])
print("Matrix = \n",A)

eigen = A.eigenvects()
print("Eigen Values , No of times repeated , Eigen Vectors\n",eigen)

A = np.array([[1,1,1],[0,2,1],[-4,4,3]])

B = np.array([[-1/2,-1,1],[1,1,0],[1,1,1]])

P = B.T
print("Modal Matrix\n",P)

Pinverse = np.linalg.inv(P)
print("Inverse of P\n",Pinverse)

D = Pinverse @ A @ P
print("Diagonal Matrix\n",D)

Matrix = 
 Matrix([[1, 1, 1], [0, 2, 1], [-4, 4, 3]])
Eigen Values , No of times repeated , Eigen Vectors
 [(1, 1, [Matrix([
[-1/2],
[  -1],
[   1]])]), (2, 1, [Matrix([
[1],
[1],
[0]])]), (3, 1, [Matrix([
[1],
[1],
[1]])])]
Modal Matrix
 [[-0.5  1.   1. ]
 [-1.   1.   1. ]
 [ 1.   0.   1. ]]
Inverse of P
 [[ 2. -2. -0.]
 [ 4. -3. -1.]
 [-2.  2.  1.]]
Diagonal Matrix
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
