In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a1 = np.arange(5,26,5)
print(a1)

[ 5 10 15 20 25]


In [8]:
mat1 = np.arange(1,10).reshape((3,3))
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
''' 
Using the correct NumPy function, create each of the following arrays. Write one line of code for each:

•	A 2×4 array filled entirely with zeros
•	A 3×3 array filled entirely with ones
•	A 4×4 identity matrix
•	A 2×2 array filled with the value 9
'''
a0 = np.zeros((2,4),dtype=int)
a1_3x3 = np.ones((3,3),dtype=int)
aI = np.eye(4,dtype=int)
a9_2x2 = np.full((2,2),9)  
print(a0)
print(a1_3x3)
print(aI)
print(a9_2x2)

[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[9 9]
 [9 9]]


In [6]:
''' 
Create an array of all even numbers from 2 to 20 (inclusive) using np.arange(). 
Then create the same sequence using np.linspace(). Print both and compare.
'''
import numpy as np
even1 = np.arange(2,21,2)
even2 = np.linspace(2,20,len(even1),dtype=int)
print(even1)
print(even2)
print(np.arange(10))
print(np.arange(0,1,0.25))
print(np.linspace(0,1,5))


[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75]
[0.   0.25 0.5  0.75 1.  ]


In [25]:
d=np.random.randint(0,51,size =(3,3))
print(d)
f = np.random.rand(2,4)
print(f)
print(f.size)
print(f.itemsize)
print(f.nbytes)

[[43 48 11]
 [46 16 20]
 [16 10 18]]
[[0.81001693 0.26750804 0.2073323  0.19411665]
 [0.93067234 0.35406081 0.81465781 0.1466427 ]]
8
8
64


In [21]:
print(np.zeros((3,3)))
print(np.empty((3,3)))
print(np.full((3,3),0))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
size = 'how many books?'
itemsize = 'how thick is each book?'
nbytes = 'total shelf space needed'

In [24]:
import numpy as np
t = np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(t.ndim)
print(t.shape)
print(t.size)


3
(2, 2, 3)
12


In [30]:
c = np.array([1, 2.5, 3]) 
print(c.dtype)
d = np.array(['Ravi', 'Priya'])
print(d.dtype)
a = np.array([0, 1, 2, 0, 5, 0]) 
print(a)
print(a.astype(float))
print(a.astype(bool))

float64
<U5
[0 1 2 0 5 0]
[0. 1. 2. 0. 5. 0.]
[False  True  True False  True False]


In [31]:
import numpy as np
a = np.array([1000, 2000, 3000], dtype=np.int8)
print(a)  # unexpected output


OverflowError: Python integer 1000 out of bounds for int8

In [34]:
import numpy as np
a = np.array([1000, 2000, 3000], dtype=np.int64)
print(a)  # unexpected output
b=np.array([1,2,3],dtype = np.int8)
print(b.itemsize)

[1000 2000 3000]
1


In [35]:
import numpy as np
a = np.array([1.9, 2.7, 3.1, 4.8])
b = a.astype(np.int32)
print(a)
print(b)
print(a.dtype, b.dtype)


[1.9 2.7 3.1 4.8]
[1 2 3 4]
float64 int32


In [38]:
d=np.arange(12).reshape(3,4)
d3 = np.arange(12).reshape(2,2,3)
print(d)
print("----------")
print(d3)
print("----------")
print(d.reshape(2,2,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
----------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [39]:
'''Use the -1 shortcut in reshape to avoid manually computing one dimension. Rewrite each reshape using -1:

a = np.arange(20)
a.reshape(4, 5)   # rewrite using -1 for the second dim
a.reshape(5, 4)   # rewrite using -1 for the first dim
a.reshape(2, 2, 5)# rewrite using -1 for the last dim'''
import numpy as np

a = np.arange(20)

a.reshape(4, -1)     # (4, 5)

a.reshape(-1, 4)     # (5, 4)

a.reshape(2, 2, -1)  # (2, 2, 5) 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [40]:
import numpy as np

a = np.array([1,2,3,4,5])

b = a[1:4]   # slice/view

b[0] = 99

print(a)
print(b)

[ 1 99  3  4  5]
[99  3  4]


In [41]:
a = np.array([1,2,3,4,5])

c = a[1:4].copy() #copy

c[0] = 99

print(a)
print(c)

[1 2 3 4 5]
[99  3  4]
