In [ ]:
import numpy as np   
import random 
'''Ravi, Priya, Arjun, Meena, Kiran appeared in 3 subjects. Their marks matrix is:

[[72, 85, 90],
 [88, 76, 82],
 [65, 91, 78],
 [90, 84, 88],
 [70, 79, 85]]
Find: subject-wise mean (axis=0), student-wise total (axis=1), and the overall class topper's total.

Expected output:

[77.   83.   84.6]
[247 246 234 262 234]
262

'''




In [ ]:
'''
Exercise 1
Create a NumPy array of integers from 1 to 10. Use boolean masking to extract all even numbers.

Exercise 2
Given the array `[15, 3, 22, 8, 47, 6, 31, 19]`, extract all elements greater than 15.

Exercise 3
Create an array `[4, 2, 7, 5, 0, 3, 1, 9]`. Use boolean masking to extract only the negative numbers.

Exercise 4
From the array `[10, 20, 30, 40, 50, 60]`, use a boolean mask to extract elements at positions where the
value is divisible by 3. (Hint: use `% 3 == 0`)



 Level 2 – Compound Conditions

Exercise 5
Given `marks = [45, 78, 92, 33, 56, 88, 71, 29]`, extract marks that are between 50 and 85 (inclusive).

Exercise 6
From the array `[3, 14, 7, 21, 5, 28, 9, 42]`, extract elements that are either less than 6 or greater than 25.

Exercise 7
Given `temps = [36.1, 37.5, 38.9, 36.8, 39.2, 37.0, 38.1]`, extract temperatures that indicate fever (above 37.5).

Exercise 8
Create a 2D array of shape (4, 4) with values 1 to 16. Use boolean masking to extract all values greater than 10.



 Level 3 – Masking with Assignment

Exercise 9
Given `scores = [45, 82, 67, 23, 91, 55, 38, 76]`, replace all scores below 50 with 0 using boolean masking.

Exercise 10
From the array `[3, -7, -1, 4, 8, -2, 5, -6]`, replace all negative values with their absolute values 
using boolean masking.

Exercise 11
Given `data = [100, 250, 430, 180, 510, 320, 95]`, cap all values above 400 to exactly 400 using boolean masking.



 Level 4 – Realworld Scenarios

Exercise 12 — Student Grades
You have two arrays:

students = ["Ravi", "Priya", "Arjun", "Meena", "Kiran"]
marks    = [72, 45, 88, 61, 39]

Use boolean masking to print the names of students who scored above 60.

Exercise 13 — Sensor Data Cleaning
A temperature sensor recorded: `[22.5, 999, 24.1, 999, 23.8, 25.0, 999, 21.9]`
The value `999` represents a faulty reading. Replace all `999` values with the mean of the valid readings.







 Bonus Challenge

Exercise 16
Given a 2D marks array:
python
marks = np.array([[55, 78, 43],
                  [90, 61, 38],
                  [47, 82, 74]])

 Find all values below 50 and replace them with 50 (pass mark)
 Count how many values were below 50 originally


'''



In [1]:
import numpy as np 
ar = np.arange(0,11)
print(ar[ar%2 == 0])

[ 0  2  4  6  8 10]


In [2]:
x = np.array([15, 3, 22, 8, 47, 6, 31, 19])
print(x[x>15])

[22 47 31 19]


In [3]:
x = np.array([4, 2, 7, 5, 0, 3, 1, 9])
print(x[x<0])

[]


In [4]:
x = np.array([10, 20, 30, 40, 50, 60])
print(np.where(x%3==0))

(array([2, 5]),)


In [6]:
marks = np.array([45, 78, 92, 33, 56, 88, 71, 29])
print(marks[(marks>50) & (marks<86)]) 

[78 56 71]


In [8]:
ar = np.array([3, 14, 7, 21, 5, 28, 9, 42])
print(ar[~((ar>6) & (ar<25))])
print(ar[(ar<6) | (ar>25)])

[ 3  5 28 42]
[ 3  5 28 42]


In [10]:
temp = np.array([36.1, 37.5, 38.9, 36.8, 39.2, 37.0, 38.1])
print("Fever:",temp[temp>37.5])

Fever: [38.9 39.2 38.1]


In [14]:
mat = np.arange(1,17).reshape(4,4)
print(mat[mat>10])

[11 12 13 14 15 16]


In [20]:
scores = np.array([45, 82, 67, 23, 91, 55, 38, 76])
# new = np.array([]) 
# print(new[np.where(scores>50,scores,0)] )
print(np.where(scores>50,scores,0))

[ 0 82 67  0 91 55  0 76]


In [21]:
marks = np.array([72, 45, 88, 61, 39])
students = np.array(["Ravi", "Priya", "Arjun", "Meena", "Kiran"])
print(students[np.where(marks>60)])

['Ravi' 'Arjun' 'Meena']


In [25]:
reading = np.array([22.5, 999, 24.1, 999, 23.8, 25.0, 999, 21.9])
mean = np.mean(reading[reading!=999])
new = np.where(reading==999,mean,reading)
print(new )

[22.5  23.46 24.1  23.46 23.8  25.   23.46 21.9 ]


In [2]:
import numpy as np    
a = np.array([3, -7, -1, 4, 8, -2, 5, -6])
ab = np.where(a<0,-a,a)
print(ab)

[3 7 1 4 8 2 5 6]


In [3]:
data = np.array([100, 250, 430, 180, 510, 320, 95] )
print(np.where(data>400,400,data))

[100 250 400 180 400 320  95]


In [4]:
'''Exercise 14 — Stock Filter

prices  = [120, 340, 89, 455, 210, 670, 150]
volumes = [500, 200, 800, 150, 600, 90, 450]

Extract prices where the price is above 200 and volume is above 300.'''
prices  = np.array([120, 340, 89, 455, 210, 670, 150])
volumes = np.array([500, 200, 800, 150, 600, 90, 450])
print(prices[np.where((prices>200) & (volumes>300))])

[210]


In [5]:
'''
Exercise 15 — Normalisation
Given `data = [10, 85, 42, 67, 5, 91, 33]`, use boolean masking to:
 Replace values below 20 with 20 (lower clamp)
 Replace values above 80 with 80 (upper clamp)
'''
data = np.array([10, 85, 42, 67, 5, 91, 33])
data[data<20] = 20
data[data>80] = 80 
print(data)

[20 80 42 67 20 80 33]


In [7]:
data = np.array([10, 85, 42, 67, 5, 91, 33])
data = np.where(data<20,20,data)
data = np.where(data>80,80,data)
print(data)

[20 80 42 67 20 80 33]


In [9]:
''' 
Bonus Challenge

Exercise 16
Given a 2D marks array:
python
marks = np.array([[55, 74, 43],
                  [90, 61, 38],
                  [47, 82, 74]])

 Find all values below 50 and replace them with 50 (pass mark)
 Count how many values were below 50 originally


'''
marks = np.array([[55, 74, 43],
                  [90, 61, 38],
                  [47, 82, 74]])
c_50 = np.sum(marks == 50)
marks[marks<50] = 50
less_than_50 = np.sum(marks == 50)-c_50
print(less_than_50)

3


In [11]:
''' BETTER APPROACH FOR ABOVE '''
marks = np.array([[55, 74, 43],
                  [90, 61, 38],
                  [47, 82, 74]])
less_than_50 = np.sum(marks<50)
marks[marks<50] = 50
print(marks)
print(less_than_50)

[[55 74 50]
 [90 61 50]
 [50 82 74]]
3
