In [9]:
import numpy as np
np.random.seed(1)
names = np.array(["a","b","c","d"])
cgpa = np.array([np.random.random()*10 for _ in range(len(names))])
cgpa = np.round(cgpa,2)
print(cgpa,names)
ind = np.argsort(cgpa)
print(np.sort(cgpa))
print(names[ind])
# print(names)
top = names[ind]
print(top)

[4.17 7.2  0.   3.02] ['a' 'b' 'c' 'd']
[0.   3.02 4.17 7.2 ]
['c' 'd' 'a' 'b']
['c' 'd' 'a' 'b']


In [6]:
# Explicit dtype
import numpy as np
a = np.array([1, 2, 3], dtype=np.float64)
print(a.dtype)      # float64
print(a)
# Type conversion
b = a.astype(np.int32)
print(b.dtype)      # int32
print(b)
print(type(b[0]))
print(type(b))

float64
[1. 2. 3.]
int32
[1 2 3]
<class 'numpy.int32'>
<class 'numpy.ndarray'>


In [27]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(a[:,1],"col 2")
print(a[1],"row 2")
print("\nsubmatrix")
print(a[1:,:2])
print()
b=np.arange(1,13)
print(b.reshape(4,3))
print(b.reshape(2,-1))
print(b.reshape(2,-1))

print(b)

print(a.flatten())
print(a)
print(a.ravel())
c=b.reshape(4,3)
print("Transpose:\n",a.T)
print("Transpose:\n",c.T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[2 5 8] col 2
[4 5 6] row 2

submatrix
[[4 5]
 [7 8]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
